spring:
  datasource.order:
    writer:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
    reader:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/order
#      username: order
#      password: order
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:

  datasource.gift:
    writer:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
    reader:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
  org.springframework.orm.jpa: DEBUG
  org.springframework.transaction: DEBUG
  org.springframework.jdbc: DEBUG

#slack:
#  bot:
#    token: xoxb-135797385811-2742300678674-9ffEYpRAzyelTcjGOR9sfXdc
#  notice:
#    channel: proj-09

slack:
  bot:
    token: xoxb-135797385811-2742300678674-9ffEYpRAzyelTcjGOR9sfXdc
  notice:
    channel: service-alert-dev-주문
